@URL = http://localhost/GABRIEL-SANMARTIN

GET {{URL}}/Categoria/Get.php

###Criar categoria
POST {{URL}}/Categoria/Create.php
Content-Type: 

{"Id": "1"
    "nome": "Palmeiras_Mundial"
}

### Atualizar Categoria
POST {{URL}}/Categoria/Update.php?Id=1
Content-Type: 

{
    "nome": "Ação melhor"
}

###Deletar usuario
GET {{URL}}/Categoria/Delete.php?Id=8

