@URL = http://localhost/GABRIEL-SANMARTIN/

GET {{URL}}/produto/get.php

###Criar produto
POST {{URL}}/produto/create.php
Content-Type: application/json

{
    "nome": "teste produto 2",
    "descricao": "produto lixoso",
    "preco": "3232",
    "quantidade": "5"
}

### Atualizar produto
POST {{URL}}/produto/update.php?id_produto=1
Content-Type: application/json

{
    "nome": "ATT",
    "descricao": "ADASDAS DADSA",
    "preco": "1",
    "quantidade": "1"
}

###Deletar produto
GET {{URL}}/produto/delete.php?id_produto=2

